const COURSES = [
    {
        id: 'analyse_numerique',
        name: 'Analyse Numérique',
        icon: 'assets/icons/analyse_numerique.png',
        type: 'math',
        folder: 'Analyse_Numerique',
        description: 'Chapitre 1 — Virgule flottante, IEEE 754 & Conditionnement',
        files: [
            {
                id: 'dashboard',
                name: 'Dashboard',
                emoji: '📊',
                type: 'dashboard',
                fcClass: 'fc-dashboard',
                desc: 'Vue d\'ensemble et suivi de progression',
                path: 'Analyse_Numerique/Dashboard_Analyse_Numerique.md',
            },
            {
                id: 'synthese',
                name: 'Fiche de Synthèse',
                emoji: '📖',
                type: 'synthesis',
                fcClass: 'fc-synthesis',
                desc: 'Chapitre 1 — Représentation & Stabilité',
                path: 'Analyse_Numerique/Synthese_Analyse_Numerique.md',
            },
            {
                id: 'exercices',
                name: 'Exercices',
                emoji: '✏️',
                type: 'exercises',
                fcClass: 'fc-exercises',
                desc: 'Exercices à difficulté croissante ⭐→⭐⭐⭐⭐⭐',
                path: 'Analyse_Numerique/Exercices_Analyse_Numerique.md',
            },
            {
                id: 'cheatsheet',
                name: 'Cheat Sheet',
                emoji: '🧾',
                type: 'cheatsheet',
                fcClass: 'fc-cheatsheet',
                desc: 'Toutes les formules du Chapitre 1',
                path: 'Analyse_Numerique/CheatSheet_Analyse_Numerique.md',
            },
            {
                id: 'flashcards',
                name: 'Flashcards',
                emoji: '🃏',
                type: 'flashcards',
                fcClass: 'fc-flashcards',
                desc: 'Révision active — mode cartes',
                path: 'Analyse_Numerique/Flashcards_Analyse_Numerique.csv',
            },
            {
                id: 'seances',
                name: 'Séances TP',
                emoji: '🏋️',
                type: 'synthesis',
                fcClass: 'fc-exercises',
                desc: 'Préparation aux séances TP — rappels & exercices similaires',
                path: 'Analyse_Numerique/Seances_Exercices_Analyse_Numerique.md',
            },
        ]
    },
    {
        id: 'informatique_oop',
        name: 'Informatique OOP',
        icon: 'assets/icons/informatique_oop.png',
        type: 'info',
        folder: 'Informatique_OOP',
        description: 'C++ — Programmation Orientée Objet (INFOH2001)',
        files: [
            {
                id: 'dashboard',
                name: 'Dashboard',
                emoji: '📊',
                type: 'dashboard',
                fcClass: 'fc-dashboard',
                desc: 'Vue d\'ensemble — Cours 1 à 3',
                path: 'Informatique_OOP/Dashboard_Informatique_OOP.md',
            },
            {
                id: 'synthese',
                name: 'Synthèse Complète',
                emoji: '📖',
                type: 'synthesis',
                fcClass: 'fc-synthesis',
                desc: 'Bases C++, Arrays, POO & Classes',
                path: 'Informatique_OOP/Synthese_Informatique_OOP.md',
            },
            {
                id: 'exercices',
                name: 'Exercices',
                emoji: '✏️',
                type: 'exercises',
                fcClass: 'fc-exercises',
                desc: 'Exercices de code à difficulté croissante',
                path: 'Informatique_OOP/Exercices_Informatique_OOP.md',
            },
            {
                id: 'cheatsheet',
                name: 'Cheat Sheet',
                emoji: '🧾',
                type: 'cheatsheet',
                fcClass: 'fc-cheatsheet',
                desc: 'Syntaxe C++ vitale pour le quiz',
                path: 'Informatique_OOP/CheatSheet_Informatique_OOP.md',
            },
            {
                id: 'flashcards',
                name: 'Flashcards',
                emoji: '🃏',
                type: 'flashcards',
                fcClass: 'fc-flashcards',
                desc: 'Révision active — mode cartes',
                path: 'Informatique_OOP/Flashcards_Informatique_OOP.csv',
            },
        ]
    },
    {
        id: 'physique',
        name: 'Physique',
        icon: 'assets/icons/physique.png',
        type: 'phys',
        folder: 'Physique',
        description: 'PHYS-H1002 — Électromagnétisme Vol. I',
        files: [
            {
                id: 'dashboard',
                name: 'Dashboard',
                emoji: '📊',
                type: 'dashboard',
                fcClass: 'fc-dashboard',
                desc: 'Vue d\'ensemble — 5 chapitres d\'électromagnétisme',
                path: 'Physique/Dashboard_Physique.md',
            },
            {
                id: 'synthese',
                name: 'Synthèse Complète',
                emoji: '📖',
                type: 'synthesis',
                fcClass: 'fc-synthesis',
                desc: 'Gradient, Flux, Faraday, Maxwell, Lenz, Circuits',
                path: 'Physique/Synthese_Physique.md',
            },
            {
                id: 'exercices',
                name: 'Exercices',
                emoji: '✏️',
                type: 'exercises',
                fcClass: 'fc-exercises',
                desc: '15 exercices à difficulté croissante ⭐→⭐⭐⭐⭐⭐',
                path: 'Physique/Exercices_Physique.md',
            },
            {
                id: 'cheatsheet',
                name: 'Cheat Sheet',
                emoji: '🧾',
                type: 'cheatsheet',
                fcClass: 'fc-cheatsheet',
                desc: 'Toutes les formules essentielles en un coup d\'œil',
                path: 'Physique/CheatSheet_Physique.md',
            },
            {
                id: 'flashcards',
                name: 'Flashcards',
                emoji: '🃏',
                type: 'flashcards',
                fcClass: 'fc-flashcards',
                desc: 'Révision active — 30 cartes Q/R',
                path: 'Physique/Flashcards_Physique.csv',
            },
        ]
    },
    {
        id: 'analyse_2',
        name: 'Analyse 2',
        icon: 'assets/icons/analyse_2.png',
        type: 'math',
        folder: 'Analyse_2',
        description: 'Chapitre 14 — Séries de Fourier (MATH-H-2000)',
        files: [
            {
                id: 'dashboard',
                name: 'Dashboard',
                emoji: '📊',
                type: 'dashboard',
                fcClass: 'fc-dashboard',
                desc: 'Vue d\'ensemble et suivi de progression',
                path: 'Analyse_2/Dashboard_Analyse_2.md',
            },
            {
                id: 'synthese',
                name: 'Fiche de Synthèse',
                emoji: '📖',
                type: 'synthesis',
                fcClass: 'fc-synthesis',
                desc: 'Chapitre 14 — Séries de Fourier (ultra-détaillé)',
                path: 'Analyse_2/Synthese_Analyse_2.md',
            },
            {
                id: 'exercices',
                name: 'Exercices',
                emoji: '✏️',
                type: 'exercises',
                fcClass: 'fc-exercises',
                desc: '12 exercices à difficulté croissante ⭐→⭐⭐⭐⭐⭐',
                path: 'Analyse_2/Exercices_Analyse_2.md',
            },
            {
                id: 'cheatsheet',
                name: 'Cheat Sheet',
                emoji: '🧾',
                type: 'cheatsheet',
                fcClass: 'fc-cheatsheet',
                desc: 'Formules vitales pour l\'examen',
                path: 'Analyse_2/CheatSheet_Analyse_2.md',
            },
            {
                id: 'flashcards',
                name: 'Flashcards',
                emoji: '🃏',
                type: 'flashcards',
                fcClass: 'fc-flashcards',
                desc: 'Révision active — 22 cartes Q/R',
                path: 'Analyse_2/Flashcards_Analyse_2.csv',
            },
            {
                id: 'seances',
                name: "Séances d'exercices",
                emoji: '🏋️',
                type: 'synthesis',
                fcClass: 'fc-exercises',
                desc: 'Rappels + exercices résolus par type (Séance 2 — Fourier)',
                path: 'Analyse_2/Seances_Exercices_Analyse_2.md',
            },
        ]
    }
];
